
version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - "80:80"

  go-backend:
    build:
      context: .
      dockerfile: Dockerfile.go-backend
    container_name: go-backend
    ports:
      - "8080:5000"

