version: '3.8'

services:
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile.go-backend
    container_name: go-backend
    ports:
      - "8080:5000"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - go-backend
