version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - go-backend

    restart: unless-stopped
  go-backend:
    build:
      context: .
      dockerfile: Dockerfile.go-backend
    container_name: go-backend
    ports:
      - "5001:5000" 
    restart: unless-stopped
